:Author: Group 5
:Email:
:Date: 09/12/2023
:Revision: version01
:License: Public Domain

= Project: {Plant Care System}

With our Project we aim to create a system that tracks certain measurements of a plant and sends them to the Arduino Cloud Platform for an individual or business to track. In total we are tracking the plant's soil humidity and environment temperature, brightness and humidity. Based on the soil humidity, we have implemented an automatic watering systems that always waters the plant when its humidity falls under a certain level. 

=== Folder structure

....
 IoTrees_Prototype_Sketch         => Arduino sketch folder
  ├── IoTrees_Prototype.ino       => main Arduino file
  ├── ReadMe.adoc                 => explaining general information of project
  ├── arduino_secrets.h           => specifiying wifi passport and secret device key to connect to cloud, only uploaded as we
                                     are working on a prototype, normally this file should be kept secret!
  ├── sketch.json                 => 
  └── thingProperties.h           => devining Things which properties will be sent to Arduino Cloud
.... 

=== BOM
To see the BOM of our project, please refer to our OneNote Project Notes:
https://1drv.ms/u/s!AgNkyD8byWtylwQwREYuiuyeChLc

=== SCHEMATIC
Schematic: https://github.com/hengweizhang/Group5-IoTrees/blob/main/IoTrees_Prototype/IIOT_Schematic.png

=== WEBSITE:
https://industrialiot.wixsite.com/iotrees


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
