// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "7bd8beb7-58eb-4eab-8624-fde70dee32e4";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


CloudTemperatureSensor air_temperature;
CloudIlluminance brightness;
int status_motor;
CloudRelativeHumidity air_humidity;
CloudRelativeHumidity soil_humidity;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME); //setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY); //setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(air_temperature, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(brightness, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(status_motor, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(air_humidity, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(soil_humidity, READ, 1 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
